### ISSUE TITLE
Which functions are you using from dependencies?

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#1]
I started to properly integrate the GUI into the package. This is done in the new branch `package`. Among other things, I renamed the folder containing the GUI. Most importantly, there is now a function `start_GUI()` that a user can call to start the GUI.

For the package, we need to be explicit which functions we import from other packages and which functions we export to the user. Can you let me know:

1. Which functions are you using from package `shinythemes`?
2. Which functions are you using from package `DT`?
3. Which functions are you using from package `flextable`? 
4. Which functions are you using from package `officer`?
5. Which functions are you using from package `vroom`?

I can show you during our regular meeting how to declare which functions are imported and exported for building the package.

**Comment by VLDrenth** [comment]
The functions that are user from each package:
1. shinytheme()
2. renderDataTable(), dataTableOutput()
3. set_flextable_defaults(), flextable(), width(), align(), padding(), hline(), add_footer_lines()
4. read_docx(), body_add_flextable()
5. vroom

shinytheme() is only used for color scheme of the app, and may be left out
