### ISSUE TITLE
Choice of location for exports not possible with browsers 

### ISSUE THREAD

**Issue by AuroreAA** [VLDrenth/robmedShiny#11]
Choice of location for exports is not possible with browsers. There are automatically downloaded to downloads folder.

**Comment by aalfons** [comment]
In external browsers, it's typically a browser setting where to put downloaded files. So it makes sense to stick with the browser setting, as this is expected behavior for the user.

**Comment by AuroreAA** [comment]
I completely agree with you, it was more of a remark.
