### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by AuroreAA** [VLDrenth/robmedShiny#12]
1. When we try to import a file that is not a csv file, the error is shown several times:

![image](https://user-images.githubusercontent.com/41582308/196176708-ace79753-8234-4536-b82e-f3de1ec3e2b5.png)

2. Apparently, there is no check about columns names about special characters or spaces. However, we have an error when we try to run the model when one variable contains spaces for example:

![image](https://user-images.githubusercontent.com/41582308/196177179-21cbfb57-d993-4f69-be7b-a793ed6766af.png)

3. Should we add a check about the delimiter of the csv file? (for example in case of space delimiter)

4. In OLS bootstrap:  “Error: invalid 'size' argument” It is not an easily “understandable” one.

**Comment by VLDrenth** [comment]
@AuroreAA
For 1. I do not seem able to reproduce the repeated error message. Would you be able to send me the file that causes this issue?
2 I have now added checks using check.names, which uses make.names when needed so that column names are always 'valid'.
3. We could replace the csv option for delimited values and then allow either csv or tsv.

**Comment by AuroreAA** [comment]
1. I have sent the data.
2. Great.
3. I am not sure if we should offer another option, @aalfons, what do you think?

**Comment by aalfons** [comment]
We could of course offer an option to define the separator for the file, but there are many other things where it could go wrong. For example, are row names stored in the file or not, how are `NA`'s encoded, and so on.

RStudio itself has a nice interface to import text data into the global environment. It might be the best option for us to scrap the support for importing CSV files from our GUI. Users can instead import a CSV file into the global environment with RStudio, and then select the data frame from the global environment in the GUI. We can show how to do those two steps in a vignette.

**Comment by AuroreAA** [comment]
I can't agree more about the first part and all the other things which can go wrong...

I think it is a very good (and convenient) idea :)

**Comment by VLDrenth** [comment]
Okay great, then I will carefully remove the csv option from the package.
