### ISSUE TITLE
Export tab for exporting tables/plot/script

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#2]
I think it will be more user friendly to have a separate tab `Export` that contains the buttons to download the table, the diagnostic plot, and the R script (in that order).

Regarding the table: If a user applied ROBMED and the OLS bootstrap, they should get one table that contains the results for both (in the current solution, the user can download separate tables). In this case, it will probably be beneficial to have an option to have the table in landscape mode (with results for ROBMED and the OLS bootstrap next to each other) or in portrait mode (with results for ROBMED and the OLS bootstrap underneath each other). However, this does not have the highest priority at the moment.

**Comment by VLDrenth** [comment]
The options for downloading have now been moved to a seperate tab; the tables for OLS and ROBMED are for now still seperate.
