### ISSUE TITLE
Options for downloaded plot

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#22]
The user should have some options for downloading the diagnostic plot:
- File format: pdf (which should be the default), png, others?
- File size: width and height, ideally the user can enter this in various measurement units (inches, cm; pixels if applicable). Setting the size in pixels may require an option for the resolution as well, I'm not sure about this.

**Comment by VLDrenth** [comment]
When creating a png a resolution is required. If not provided R uses a default of 72 ppi, which looks a bit too pixelated. Choosing the right width and height in pixels feels unpredictable, so I think it may be better to only let users choose size in cm and inches and also let them choose the resolution.

I don't think other formats are needed; the plots are small files so there is no reason to provide lossy options like JPEG.

**Comment by aalfons** [comment]
Sounds good to me.
