### ISSUE TITLE
Inputs for downloading diagnostic plot

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#24]
The inputs for downloading the diagnostic plot in the `Export` tab can benefit from some changes and reordering:

1. For the file format, change "File format plot" to "File format". It's simpler, and since it's in the section for the diagnostic plot, it's clear that this is the file format for the plot.
2. I don't think that the sliders work well as input for the width and height of the plot. It looks rather strange when the units are changed, and it currently only works in increments of 1 (which is too large for inches). I think numeric input boxes work better, since the user can enter the size precisely (for example, 3.125 inches).
3. The input for the resolution should only be displayed when the file format is `png`, and it should be displayed below the inputs for width and height. Perhaps the resolution should also be converted, since 300 pixels per inch are very different from from 300 pixels per cm.

**Comment by VLDrenth** [comment]
1 and 2 are now implemented. For 3 I think it might be better to only have pixels per inch as option rather than add pixels per cm, as this seems to be the standard unit for png 'quality'.

**Comment by aalfons** [comment]
Thanks, I agree about using ppi. However, the box for the resulution should be below the boxes for width and height. You can also simplify the names of the input boxes to "Width", "Height", and "Resolution (ppi)". The inputs are grouped under the header "Diagnostic plot" and above the button "Download plot". It is clear that they refer to the plot, we don't have to repeat that so many times.
