### ISSUE TITLE
Progress bar for long computation time

### ISSUE THREAD

**Issue by AuroreAA** [VLDrenth/robmedShiny#26]
It would be nice to have progress bars for running the model and/or downloading plots. 
My first thought would be to use the ` withProgress` [function](https://shiny.rstudio.com/articles/progress.html) and you do not need to details the `incProgress`. But just to let you know, it exists quite a lot of fancy progress bars as well (see the package `shinybusy` for [example](https://dreamrs.github.io/shinybusy/articles/shinybusy.html)).

In addition, maybe it can be good to include the computation of pvalues when running the model.

**Comment by aalfons** [comment]
For the p-values, I see two options:
1. We compute them in the background (after the output of summary is shown). I'm not sure if this will block that the user from doing anything else in the GUI until the p-values are computed.
2. We can include a checkbox in the GUI whether to include p-values in the table, with a warning that they take a bit of time to compute.

**Comment by VLDrenth** [comment]
No progress bar has been implemented, but a popup is shown stating that it is being computed. For the p-values, there is a checkbox but this does not apply to the latex table at the moment.
