### ISSUE TITLE
Information mediation models in model tab

### ISSUE THREAD

**Issue by VLDrenth** [VLDrenth/robmedShiny#32]
When a user specifies more than 1 mediator in their model, they are forced to choose the mediatior model nothing is automatically selected. They can leave this input empty, but when running either test, a message is shown telling the user they need to select a mediatior model. 

1. Is this a fine solution, or should we make it clear/require in the model tab that this input is absolutely necessary?
2. Currently there is no explanation on the mediation models given in the app. Would it be good to add an overview of the mediation models in the model tab to explain what option they should pick; there is ample space available there as well. And if we do so, what should we include there?

**Comment by aalfons** [comment]
Good points, thanks. I like in particular your suggestion to include some information on the mediation models.

1. The parallel mediator model is more commonly used than the serial mediator model, so the former could be the default. This would also mirror the behavior of the command line function, where the parallel mediator model is the default.
2. The different mediator models are described in the help file of `robmed::test_mediation()`. We could copy those descriptions to the `Model` tab of the GUI. (I'm not sure if there is a nice way to access the corresponding section of the help file directly such that the GUI is updated automatically when we make a change in the help file.) It might also be helpful to include diagrams such as the ones in Section 2.1 of the JSS paper. I can provide those diagrams.
