### ISSUE TITLE
Aligning column in xtable

### ISSUE THREAD

**Issue by VLDrenth** [VLDrenth/robmedShiny#33]
```
library(robmed)
library(flextable)
library(xtable)

ctrl <- reg_control(efficiency = "0.85", max_iterations = 10000)

robust_boot <- test_mediation(BSG2014, x = "TaskConflict",
                              y = "ProcessConflict",
                              m = "SharedExperience",
                              robust = TRUE,
                              level = 0.95,
                              R = 5000,
                              control = ctrl)

to_latex(robust_boot, digits = 4)
```

When running the above code and compiling the resultant LaTeX code I get the following table:
[
![latex_reprex](https://user-images.githubusercontent.com/44548827/204363584-11e2ea9e-ee44-4c8a-9b11-240cbedef3ee.jpg)

This is close to what I am aiming for, but I cannot seem to find a good solution for aligning the column of the confidence interval with the columns of the standard error and z-statistic. 
I have tried using horizontal blank spaces but this pushed the p-value column out of the document.
Does anyone have a good suggestion on how to do this?

**Comment by AuroreAA** [comment]
Indeed, that can be tricky to do so for latex... However, a naive approach would be to split the 'Confidence Interval' column into two columns (V3 and V4): 'Confidence' and 'Interval', and then you put '(-0.2086,' in V3 and '0.0239)' in a second one...

By the way, I am not sure if it is better but you have also the `xtableList` which can be useful when you have a list of data frames. In addition the `add.to.row` parameters can maybe be useful to add the second table there with some multicolumn instructions (but not sure if it is really possible).

**Comment by VLDrenth** [comment]
xtableList did not really work for me as it seems to require the column names to be the same for the tables. I'll try looking into using add.to.row next.

**Comment by aalfons** [comment]
There's a simple way to align the columns, we don't need to resort to a hack. We can use `\multicolumn{2}{c}{Text}`. Within the first set of curly braces, you specify how many columns the cell should span, within the second the alignment within the cell, and within the third the content of the cell. See also https://en.wikibooks.org/wiki/LaTeX/Tables.

**Comment by aalfons** [comment]
On another note, can you please make the first column left-aligned?
