### ISSUE TITLE
Assigning objects in script

### ISSUE THREAD

**Issue by VLDrenth** [VLDrenth/robmedShiny#34]
In the generated R script we need to assign the return value of a call to test_mediation to an object.
 Currently this is done by pasting "robust_boot <- " and as.character(as.expression(command_robust_bootstrap_test)).
 Is there a way to do this without pasting, instead using a call/expression?

**Comment by aalfons** [comment]
In fact, we can work with a second function call here. First, it's important to understand that we can write the assignment
```
x <- 1
```
also in the following way:
```
"<-"(x, 1)
```
This looks absolutely horrible and no one in their right mind would use it like this, but I'm showing you this to highlight that operators are just functions that have a short-cut in terms of notation.

So in the example that I gave in #25 , we have a list of inputs
```
input <- list(df_name = "BSG2014", x = "ValueDiversity", y = "TeamCommitment", m = "TaskConflict")
```
and we first build the function call to `test_mediation()` with
```
function_call <- call("test_mediation", as.name(input$df_name), x = input$x, y = input$y, m = input$m)
if (!is.null(input$covariates)) function_call$covariates <- input$covariates
```
With this function call, we can complete the command by creating another function call for the assignment:
```
command <- call("<-", as.name("robust_boot"), function_call)
```
The result looks like this:
```
robust_boot <- test_mediation(BSG2014, x = "ValueDiversity", 
    y = "TeamCommitment", m = "TaskConflict")
```

With this, we can evaluate the command with `eval(command)` to generate the output in the shiny app, and we can use `as.character(as.expression(command))` to convert it to a text string to be exported to the R script.
