### ISSUE TITLE
Order of inputs in tabs ROBMED and OLS Bootstrap

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#4]
The order of inputs in the `ROBMED` tab should reflect the importance such that the most relevant inputs are on top. Please rearrange the inputs in this order (from top to bottom), with headers (here in bold) to group different inputs:

**Options**
Confidence level
Number of bootstrap samples
**Random number generator**
Seed
Version
**MM-estimator**
Efficiency at normal distribution
Maximum number of iterations

Please use those exact names from above for the inputs. The `OLS Bootstrap` tab should have the first four inputs in the same order.

Also note that the input for the version of the random number generator should be in the tabs `ROBMED` and `OLS Bootstrap` (controlling the same variable) and not in the `Data and Model` tab.

Finally, the input for the Version of the random number generator should be a simple text box where the user can enter the desired version number. If no version number is entered, it simply uses the current random number generator. (Now you hardcode the different version numbers into the box for selecting one option, which means that this would be manually changed every time there is a new R version).

**Comment by VLDrenth** [comment]
The suggested enhancements have all been incorporated

**Comment by aalfons** [comment]
@VLDrenth, I reopened this because the order of the inputs for the OLS bootstrap is different than for ROBMED. For the OLS bootstrap, the confidence level should come before the number of bootstrap samples (just like for ROBMED).
