### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#5]
Consistent coding style is important not only for long-time maintenance of the package, but it also makes it easier to find bugs. I therefore have some suggestions.

1. Don't have more than 80 characters on a line of code. Long lines make it more difficult to see everything on one line, making it more difficult to find bugs. In particular when one is working on a laptop with a smaller screen, one would need to sidescroll to see certain parts of code, which makes it extremely difficult to find bugs. You can set up RStudio to display a vertical line at 80 characters for this purpose (_Tools -> Global Options -> Code -> Display_ tab, check the option _Show margin_ and set _Margin column_ to 80).

2. Always use `<-` for assignment. Currently, you sometimes use `<-` and sometimes `=`. While the two are interchangeable in 99% of cases, there are differences in their behavior. Hence it's best to keep `<-` for assigning an object, and use `=` only to set arguments.

3. Similarly, always use double quotes (`"`) for text strings. A valid exception is when you need to use quotes within a text string, but let's not get into that now. If you sometimes use double quotes and sometimes use single quotes, it's easy to introduce bugs when you make changes (e.g., using a single quote to close a text string that was opened with a double quote). In general consistency always makes things easier in the long run.

4. Object names: Use underscores to separate words, and use them consistently. Currently, you use underscores most of the times, but sometimes you use capital letters to start a new word, other times you write some words together without underscores.

Bad:
```
dataframeName = input$dfname
final_df <- as.data.frame(get(input$dfname, .GlobalEnv))
```
Good:
```
df_name <- input$df_name
final_df <- as.data.frame(get(input$df_name, envir = .GlobalEnv))
```

Bad:
```
txt_formulamodel
```
Good:
```
txt_formula_model
```

5. Indentation: Messy indentation can make it very hard to find bugs such as missing parentheses or curly braces. Always use two spaces for a new level of indentation, or in case of a function call you can also align the next line with the opening parentheses. Note that with RStudio, you can clean up the indentation in and R file with the keyboard shortcut `Ctrl+I`.

Good: 
```
mainPanel(
  verbatimTextOutput('CI'),
  h3("Model and Test summary"),
  verbatimTextOutput('summaryOLS')
)
```
Also good (note that the closing parentheses are not on a separate line):
```
mainPanel(verbatimTextOutput('CI'), 
          h3("Model and Test summary"),
          verbatimTextOutput('summaryOLS'))
```
Bad (indentation of closing parentheses is not correct):
```
mainPanel(
  verbatimTextOutput('CI'),
  h3("Model and Test summary"),
  verbatimTextOutput('summaryOLS')
  )
```
Bad (just a mess):
```
mainPanel(
    verbatimTextOutput('CI'),
 h3("Model and Test summary"),
  verbatimTextOutput('summaryOLS')
       )
```
Bad (runaway closing parentheses; when you edit the file later and add a new command, it can easily happen to put it in the wrong line so that the new command is entered inside the `mainPanel()` command instead of after it):
```
mainPanel(verbatimTextOutput('CI'), 
          h3("Model and Test summary"),
          verbatimTextOutput('summaryOLS')
          )
```

6. In production code, it's good practice to be explicit with argument names. You can omit the name for the first argument, or if you use both the first and second argument of a function, but I'd explicitly use argument names in all other instances. Functions can change over time, and new arguments can be added that can break the code. See also the example above, where I explicitly added the `envir` argument of function `get()`.

**Comment by AuroreAA** [comment]
For maintenance, I like to have sections in the script but it depends on people. In addition, I also like to put the name of the package before the name of the function used: package::function
