### ISSUE TITLE
Making repository private while GUI is in development

### ISSUE THREAD

**Issue by aalfons** [VLDrenth/robmedShiny#6]
Perhaps it's a good idea to make the repository private until we're ready to share it with the world? Thanks @AuroreAA for catching and suggesting this.

**Comment by aalfons** [comment]
@VLDrenth, can you please make the repository private for now?

**Comment by VLDrenth** [comment]
@aalfons I cannot directly change the visiblity of the repository, because it is a fork according to Github. It seems the easiest way to solve this is to import the repo into a new, private one. Shall I do that instead?

**Comment by aalfons** [comment]
Let's not create a new repository. That might be messy when we want to pull the functionality into the main repository (on my account).
