### ISSUE TITLE
Default tables/plot/script names are not consistent

### ISSUE THREAD

**Issue by AuroreAA** [VLDrenth/robmedShiny#9]
1. Default tables/plot/script names are not consistent in terms of pattern, use of lower/upper case and type of output (plot, script, table?)

- 2022-10-11plot
- 2022-10-11ROBMEDoutput
- 2022-10-11-Script

2. In case we click a second time on the download R script button, the default name becomes: downloadScript

3. Extension of files disappeared when we change the name.

4. Choice of location for exports is not possible with browsers. There are automatically downloaded to downloads folder.

**Comment by VLDrenth** [comment]
1. I have changed the names to: <date>diagnosticplot, <date>table(OLS/ROBMED), <date>script.
2. This issue should now be resolved
3. Occurs only when running locally for me; in browser this does appear to happen
4. I believe this depends on the user's browser settings; for me the option is the same as when running in window
